### ISSUE TITLE
When I http://127.0.0.1:1127/view/id I get Error

### ISSUE THREAD

**Issue by kefeibuhuifei** [electron/mini-breakpad-server#21]
When I http://127.0.0.1:1127/view/id I get Error
at ChildProcess. <anonymous> (E: \ mini-breakpad-server \ node_modules \ minidump \ lib \ minidump.js: 41: 25)

**Comment by kefeibuhuifei** [comment]
![image](https://user-images.githubusercontent.com/33917095/76086610-65ebdc00-5fef-11ea-8238-4c5d7ebc8b66.png)

**Comment by huwei365** [comment]
I met the same problem.

Error
    at ChildProcess.<anonymous> (D:\repositorys\mini-breakpad-server\node_modules\minidump\lib\minidump.js:41:25)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by GuitarChen** [comment]
> I met the same problem.
> 
> Error
> at ChildProcess. (D:\repositorys\mini-breakpad-server\node_modules\minidump\lib\minidump.js:41:25)
> at ChildProcess.emit (events.js:311:20)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

do you resolve after?

**Comment by huwei365** [comment]
> > I met the same problem.
> > Error
> > at ChildProcess. (D:\repositorys\mini-breakpad-server\node_modules\minidump\lib\minidump.js:41:25)
> > at ChildProcess.emit (events.js:311:20)
> > at maybeClose (internal/child_process.js:1021:16)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 
> do you resolve after?

no, I wrote a new server, use golang.

**Comment by GuitarChen** [comment]
> > > I met the same problem.
> > > Error
> > > at ChildProcess. (D:\repositorys\mini-breakpad-server\node_modules\minidump\lib\minidump.js:41:25)
> > > at ChildProcess.emit (events.js:311:20)
> > > at maybeClose (internal/child_process.js:1021:16)
> > > at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> > 
> > 
> > do you resolve after?
> 
> no, I wrote a new server, use golang.

so sad

**Comment by GuitarChen** [comment]
i resolve it that i put cygwin1.dll；cygstdc++-6.dll；cyggcc_s-1.dll to “.\mini-breakpad-server\node_modules\minidump\deps\breakpad”。somebody tell me in minidump issues that minidump_stackwalk.exe need these dlls to work in windows

**Comment by huwei365** [comment]
> 
> 
> i resolve it that i put cygwin1.dll；cygstdc++-6.dll；cyggcc_s-1.dll to “.\mini-breakpad-server\node_modules\minidump\deps\breakpad”。somebody tell me in minidump issues that minidump_stackwalk.exe need these dlls to work in windows

well done!
